public class Example{
    // variables
    String name; Integer protonTorpedoes;Integer deathStarsDestroyed;Decimal powerRemaining;User pilot; Account manufacturer;
    //LaserCannon lasers;HyperdriveEngine engine; DeflectorShield Shield; AstromechDroid droid;
    
    public void shootLasers(Integer numberOfShots){
        for (Integer i = 0; i < numberOfShots; i++){
            
            System.debug('Pew!');
        }
        
    }
   
    
}